[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "langchain>=0.3.27",
    "langgraph>=0.6.6",
    "langsmith>=0.4.16",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
]
